fastp:
 compression_level: "9"
 general: "--disable_length_filtering"

kraken:
 general: "--output - --fastq-input --gzip-compressed --paired"
 db: "/home/vdputten/kraken_db_nohuman"

shovill:
 minlen: "500"
 ram: "64"
 depth: "100"
 assembler: "spades"
 tmpdir: "$TMPDIR"

abricate:
 minid: "90"
 mincov: "60"
 ncbi: "ncbi"
 vfdb: "vfdb"
 plasmidfinder: "plasmidfinder"
 ecoh: "ecoh"

amrfinder:
 organism: "Escherichia"

prokka:
 general: "--usegenus"
 kingdom: "Bacteria"
 genus: "Escherichia"
 species: "coli"

snippy:
 general: "--force --cleanup"
 ATCC25922_ST69: "references/ATCC25922.gbk"
 K12_ST10: "references/K12.gbk"
 DSM30083_ST95: "references/DSM30083.gbk"

snippycore:
 prefix: "COMBAT"

iqtree:
 prefix: "COMBAT"

filtlong:
 target_bases: "500000000"
 keep_percent: "100"

print_travelers_withST38:
 threshold_verylikely: "8"
 threshold_likely: "17"

print_travelers_withoutST38:
 threshold_verylikely: "13"
 threshold_likely: "17"
